# Generated by Django 4.1.3 on 2022-12-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("link", models.CharField(max_length=225)),
                ("photo", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("number", models.FloatField()),
                ("create_date", models.DateField(auto_now_add=True)),
            ],
            options={"db_table": "hotle",},
        ),
        migrations.CreateModel(
            name="Hotelchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50)),
            ],
            options={"db_table": "city",},
        ),
    ]
