# Generated by Django 4.1.3 on 2022-12-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="hotel", name="address",),
        migrations.AddField(
            model_name="hotel",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
